### PR TITLE
Add calcite snippet

### PR DESCRIPTION
**Pull request by libertadcc**
I use a lot of Calcite and I think it can be useful for more people.

### CODE REVIEW

**Comment by RalucaNicola** [comment]
Looks good to me, tried it out locally. @kellyhutchins can you also have a look?

**Review by kellyhutchins — COMMENTED** [review]
For the cdn paths in the html.json file it might be helpful to add placeholders for the version so users can quickly update to the latest. You can see an example of how this looks in the html.json file here: 
https://github.com/Esri/arcgis-js-vscode-snippets/blob/e7c5b57ec274bfca43f002c7180f02fb9d7a7d76/snippets/html.json#L6

**Comment by libertadcc** [comment]
Thanks! It is a good idea but I have been going through the [documentation](https://developers.arcgis.com/calcite-design-system/get-started/)  and I cannot find previous versions. Do you know where they are named? Thanks! :)

**Comment by hhkaos** [comment]
I guess you need to take them [from the repo](https://github.com/Esri/calcite-components/releases), right now I only see two: `${1|1.0.0-beta.52,1.0.0-next.218|}`

**Pull request merged**
